# Generated by Django 4.1.3 on 2022-12-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0003_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
